version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/src

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
