version: '3.8'

services:
  eventfor:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uwsgi --ini src/uwsgi.ini
    volumes:
      - .:/src
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/src/static
    depends_on:
      - eventfor

volumes:
  postgres_data:
