version: '3.8'

services:
  backend:
    image: gcr.io/${GCP_PROJECT}/eventfor.us-backend:latest
    command: uwsgi --ini src/uwsgi.ini
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src/logs:/app/src/logs

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/static:/app/src/static
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificates/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./certificates/private_key.pem:/etc/ssl/private/private_key.pem:ro
    depends_on:
      - backend

volumes:
  postgres_data:
