FROM python:3.11-slim as base

ENV APP_HOME=/src

RUN apt-get update \
    && apt-get install -y build-essential netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*


FROM base as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock /tmp/
RUN poetry export --output requirements.txt


FROM base as development

WORKDIR $APP_HOME

COPY --from=requirements-stage /tmp/requirements.txt $APP_HOME/
RUN pip install --upgrade -r requirements.txt

COPY ./scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
